### PR TITLE
Now bookings can be created from wizard

### LINKED ISSUE #7: Wizard does not create bookings
## Problem 
Cannot create bookings from the wizard.

## Steps to reproduce
- Open page with booking wizard. 
- After that select service, day and session you want to book. 
- Press "Add to Cart". 
- Observe problem.

## Solution
Implement "Add to cart" button press by adding endpoint information to wizard client.

### PR DESCRIPTION
**Pull request by romalytvynenko**
fixes #7 

P.S.: As you can see, branch name is task/*2*_... but closed issue has number 7. This is because the issue was created in different repository and had number 2 when I started working on it. For now I've closed issue in that repo and reopened the new one in this repo (number 7).

### CODE REVIEW

File: src/components/BookingWizard/BookingWizard.vue [hunk 1]
```diff
@@ -40,13 +41,15 @@
             {{ $_('Back') }}
           </wizard-button>
 
-          <wizard-button @click.native="props.isLastStep ? alert('Done') : props.nextTab()"
+          <wizard-button @click.native="props.isLastStep ? createBooking() : props.nextTab()"
```
Comment (XedinUnknown) [inline src/components/BookingWizard/BookingWizard.vue]: Next time, when we create templates for things that will work only in the future, use a real method here straight away, and then change what it does later.

File: src/services/config/index.js [hunk 2]
```diff
@@ -10,10 +10,15 @@ const dateFormats = {
...
 }
 
+const bookingStatusTransitions = {
+  cart: 'cart'
+}
+
 di.service('config', function () {
   return {
     appEl: '#app',
     'API_BASE_URL': 'http://127.0.0.1:8000',
```
Comment (XedinUnknown) [inline src/services/config/index.js]: Looks like development URL. Is it used? This should probably come from the server somehow.

File: src/store/modules/sessions/sessionTransform.js [hunk 3]
```diff
@@ -25,6 +25,8 @@ export const prepareSessionObject = (session: Object, service: Object) => {
   const uId = getSessionUniqueKey(session)
   session['_id'] = uId
   session['serviceId'] = service.id
+  session['_start'] = session.start
```
Comment (XedinUnknown) [inline src/store/modules/sessions/sessionTransform.js]: Why do some property names start with an underscore, and some don't? What is exactly the set that we are using? Right now, it's hard to understand if we are supplying extra/lacking data, and therefore how this can be made better.

File: src/services/config/index.js (hunk 2 above)
Comment (romalytvynenko) [reply src/services/config/index.js]: Config is already coming from backend, so this base url is changed.

File: src/store/modules/sessions/sessionTransform.js (hunk 3 above)
Comment (romalytvynenko) [reply src/store/modules/sessions/sessionTransform.js]: Yes, you are right. I'll change it.

Comment (romalytvynenko) [reply src/store/modules/sessions/sessionTransform.js]: @XedinUnknown 
I removed extra data and now I transform timestamp to ISO when it is needed.
